### ISSUE TITLE
No-GUI option does not generate any output

### ISSUE THREAD

**Issue by Sachmet-Netjer** [raid-toolkit/extractor#1]
Hi,

after switching to the new extractor it seems --nogui and/or -g do not create neither the standard file artifacts.json nor a with option -o specified output file.

Regards Efro

**Comment by zerfl** [comment]
This was fixed in https://github.com/raid-toolkit/extractor/commit/14b3fb4312775cb18ad65c321c1c0a56f9764b9f.

Thanks for the report.
